version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '5000:5000'
    env_file:
      - .env
    volumes:
      - images_data:/app/Images
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  images_data:
